### ISSUE TITLE
add git tag version info in the proto docs

### ISSUE THREAD

**Issue by hellt** [nokia/srlinux-ndk-protobufs#3]
The main heading of the HTML proto docs page should indicate which API version is this.

![image](https://user-images.githubusercontent.com/5679861/144764655-873d0d27-b9f3-49c9-8400-5a297353943d.png)

/cc @siva19susi

**Comment by siva19susi** [comment]
@hellt None of the NDK files provide the release information. So where do we source it from to add into the HTML page (via the template) ?

**Comment by hellt** [comment]
@siva19susi from the user-provided argument I think

**Comment by hellt** [comment]
done in #4
